### ISSUE TITLE
/transfercar works but color and all mods getting reset 

### ISSUE THREAD

**Issue by TheOldHook** [hhfw1/hh_vehextras#3]
Hello, 

I added the script with the updated code for qb-core. 
Everything works except that the custom color, turbo, engine and all other mods get reset when car is placed in garage and taken out again. 

In the console you can clearly see this happening:
`[      script:oxmysql] [WARNING] hh_vehextras took 429.910486ms to execute a query!
[      script:oxmysql]       INSERT INTO player_vehicles (license, citizenid, vehicle, hash, mods, plate, state) VALUES (?, ?, ?, ?, ?, ?, ?) [null,"ODF18542","f15078",77525437,"\"{\\\"modBrakes\\\":-1,\\\"modStruts\\\":-1,\\\"wheelColor\\\":156,\\\"modArmor\\\":-1,\\\"modFender\\\":-1,\\\"modTrimA\\\":-1,\\\"modRearBumper\\\":-1,\\\"modSideSkirt\\\":-1,\\\"modXenon\\\":false,\\\"plateIndex\\\":2,\\\"modOrnaments\\\":-1,\\\"modGrille\\\":-1,\\\"bodyHealth\\\":1000.0592475178704,\\\"modSpoilers\\\":-1,\\\"extras\\\":{\\\"1\\\":false,\\\"2\\\":true,\\\"5\\\":false,\\\"3\\\":false,\\\"4\\\":false},\\\"modCustomTiresR\\\":false,\\\"dirtLevel\\\":0.0,\\\"modAirFilter\\\":-1,\\\"modWindows\\\":-1,\\\"color2\\\":111,\\\"neonColor\\\":[255,0,255],\\\"windowTint\\\":-1,\\\"pearlescentColor\\\":0,\\\"modTrimB\\\":-1,\\\"modEngine\\\":3,\\\"modFrame\\\":-1,\\\"modRoof\\\":-1,\\\"modSuspension\\\":-1,\\\"modEngineBlock\\\":-1,\\\"modTurbo\\\":1,\\\"modRightFender\\\":-1,\\\"modHorns\\\":-1,\\\"modBackWheels\\\":-1,\\\"modShifterLeavers\\\":-1,\\\"modTank\\\":-1,\\\"modDoorSpeaker\\\":-1,\\\"fuelLevel\\\":79.43282347242814,\\\"modLivery\\\":-1,\\\"tyreSmokeColor\\\":[255,255,255],\\\"modTrunk\\\":-1,\\\"modSpeakers\\\":-1,\\\"modCustomTiresF\\\":false,\\\"neonEnabled\\\":[false,false,false,false],\\\"wheels\\\":4,\\\"modExhaust\\\":-1,\\\"modSeats\\\":-1,\\\"xenonColor\\\":255,\\\"modPlateHolder\\\":-1,\\\"engineHealth\\\":1000.0592475178704,\\\"modArchCover\\\":-1,\\\"modDial\\\":-1,\\\"interiorColor\\\":111,\\\"modAPlate\\\":-1,\\\"model\\\":77525437,\\\"modFrontBumper\\\":-1,\\\"plate\\\":\\\"1XG932YA\\\",\\\"modVanityPlate\\\":-1,\\\"modAerials\\\":-1,\\\"modHood\\\":-1,\\\"dashboardColor\\\":111,\\\"modSteeringWheel\\\":-1,\\\"modHydrolic\\\":-1,\\\"modDashboard\\\":-1,\\\"tankHealth\\\":4000.2369900714818,\\\"modSmokeEnabled\\\":false,\\\"modFrontWheels\\\":-1,\\\"color1\\\":27,\\\"modTransmission\\\":-1}\"","1XG932YA",0]`

**Comment by hhfw1** [comment]
Fixed
